//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeverageManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public byte ConfigID { get; set; }
        public int PerCyclePerson { get; set; }
        public int LastEmployeeID { get; set; }
        public int CurrentRunningCycle { get; set; }
    }
}
