//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BeverageManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Histories = new HashSet<History>();
        }
    
        public int EmployeeID { get; set; }

       [StringLength(50)]
        public string Name { get; set; }
        [Display(Name = "Working Condition")]
        public bool IsWorking { get; set; }
        public int Cycle { get; set; }
        [StringLength(255)]
        public string Email { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public System.DateTime LastPaymentDate { get; set; }
        public virtual ICollection<History> Histories { get; set; }
    }
}
