//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeverageManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int HistoryID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Dated { get; set; }
        public int WeekNumber { get; set; }
        public int Amount { get; set; }

        public virtual Employee Employee { get; set; }
    }
}
